### ISSUE TITLE
Column Type Conversion

### ISSUE THREAD

**Issue by jessica-pack** [DJGump/module-work-DSI06#1]
The function formatting and converting 'object' type columns to numbers does not account for negatives and percents.

**Comment by ghost** [comment]
fort_conv = fort.replace({"\$": "", ",": "", "\%": ""}, regex=True) #gets rid of problem characters

fort_conv = fort_conv.apply(pd.to_numeric, axis=0, errors="coerce") #force convert

fort_conv = fort_conv.dropna(axis="columns", how="all") #get rid of columns that have all NaN


cols = fort_conv.columns

final_fort = fort #make a copy of original

for i in fort_conv.columns: #replace columns to maintain an complete database comparable to original
    final_fort[i] = fort_conv[i]

**Comment by ghost** [comment]
formatting is shit but hopefully you'll still be able to work it out

**Comment by AdamSpannbauer** [comment]
I didn't actually copy down the code and run it.  So this is some at a glance code review rather than a rigorous review.


#### Note on `regex=True` in `.replace()`

The `$` is a special character in regex that means 'the end of the string'.  For example, the regex `'s$'` is saying find an `s` that's at the end.  To ask to find a literal backslash, rather than the end of the string we'll want to escape the `$` like `'\$'`.  Regex has other reserved characters to watch out for as well.  To see more of these at a glance, you can check the quick reference section in the bottom right hand corner of [regex101.com](https://regex101.com/).

#### Note on copying dataframes

Assigning a dataframe to a new name will not make a copy.  The below example will add the column `'x'` to the `iris` dataframe despite assigning to `iris2`.  Use the dataframe `.copy()` method to create a copy and avoid this behavior.

```python
import seaborn as sns

iris = sns.load_dataset("iris")

iris2 = iris
iris2["x"] = 1

iris.head()
```

#### Note on code formatting in markdown

To format code in markdown you can use triple backtick example syntax:

    ```
    paste your code here
    ```

To make it syntax highlighted you can put the name of the language next to the first triple backtick

    ```python
    paste your python code here
    ```

**Comment by ghost** [comment]
ah. I used the good ol' trial and error without looking at what regex is really doing. Just found that it worked with regex and didn't work without it. 

Thanks for taking a look though. Definitely very helpful.

**Comment by jessica-pack** [comment]
Added regex=False parameter to str.replace() calls to preserve necessary formatting of  in change columns.
